In [1]:
!conda install numpy

Solving environment: ...working... done

# All requested packages already installed.



In [5]:
#!pip install numpy

In [3]:
!conda --version

conda 4.8.5


In [4]:
!conda list numpy

# packages in environment at C:\Users\Iqbal\anaconda3:
#
# Name                    Version                   Build  Channel
numpy                     1.18.5           py38h6530119_0  
numpy-base                1.18.5           py38hc3f5095_0  
numpydoc                  1.1.0                      py_0  


In [6]:
!conda list

# packages in environment at C:\Users\Iqbal\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0  
alabaster                 0.7.12                     py_0  
anaconda                  2020.07                  py38_0  
anaconda-client           1.7.2                    py38_0  
anaconda-navigator        1.9.12                   py38_0  
anaconda-project          0.8.4                      py_0  
argh                      0.26.2                   py38_0  
asn1crypto                1.3.0                    py38_0  
astroid                   2.4.2                    py38_0  
astropy                   4.0.1.post1      py38he774522_1  
atomicwrites              1.4.0                      py_0  
attrs                     19.3.0                     py_0  
autopep8                  1.5.3                      py_0  
babel                     2.8.0                      py_0  
backcall                  0.2.0     

Array

In [12]:
import numpy as np

In [13]:
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
print(arr1[0]) #untuk mengambil kolom ke 1
print(arr1[1]) #untuk mengambil kolom ke 2
print(arr1[2]) #untuk mengambil kolom ke 3

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [28]:
print(arr1[0, 2]) #untuk mengambil kolom ke 1 baris ke 3
print(arr1[1, 1]) #untuk mengambil kolom ke 2 baris ke 2
print(arr1[:, 0]) #untuk mengambil semua kolom di baris ke-1

3
6
[1 5 9]


In [29]:
arr1.dtype

dtype('int32')

In [41]:
#shape of array
print("Shape of array :", arr1.shape)
print("Dimension of array :", arr1.ndim)


print("Shape of array :", arr2.shape)
print("Dimension of array :", arr2.ndim)

Shape of array : (3, 4)
Dimension of array : 2
Shape of array : (2, 3, 3)
Dimension of array : 3


In [40]:
arr2 = np.array([
    [
        [1, 2, 3],
        [11, 22, 33],
        [111, 222, 333]
    ],
    [
        [4, 5, 6],
        [44, 55, 66],
        [444, 555, 666]
    ]
])
print(arr2)

[[[  1   2   3]
  [ 11  22  33]
  [111 222 333]]

 [[  4   5   6]
  [ 44  55  66]
  [444 555 666]]]


In [45]:
arr_zeros_1 = np.zeros(10)
arr_zeros_2 = np.zeros((10, 5))
arr_zeros_3 = np.zeros([5, 10, 10])

print(arr_zeros_1)
print("--")
print(arr_zeros_2)
print("--")
print(arr_zeros_3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
--
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
--
[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0.

In [46]:
arr_ones_1 = np.ones(5)
arr_ones_2 = np.ones((5, 5))
arr_ones_3 = np.ones([5, 6, 10])

print(arr_ones_1)
print("--")
print(arr_ones_2)
print("--")
print(arr_ones_3)

[1. 1. 1. 1. 1.]
--
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
--
[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1

In [51]:
arr_empty = np.empty((250, 10000))
print(arr_empty)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [59]:
arr_arange_1 = np.arange(50, 750, 5)
print(arr_arange_1)

[ 50  55  60  65  70  75  80  85  90  95 100 105 110 115 120 125 130 135
 140 145 150 155 160 165 170 175 180 185 190 195 200 205 210 215 220 225
 230 235 240 245 250 255 260 265 270 275 280 285 290 295 300 305 310 315
 320 325 330 335 340 345 350 355 360 365 370 375 380 385 390 395 400 405
 410 415 420 425 430 435 440 445 450 455 460 465 470 475 480 485 490 495
 500 505 510 515 520 525 530 535 540 545 550 555 560 565 570 575 580 585
 590 595 600 605 610 615 620 625 630 635 640 645 650 655 660 665 670 675
 680 685 690 695 700 705 710 715 720 725 730 735 740 745]


In [105]:
arr_one = np.array([1, 2, 3, 4, 5])
arr_one

array([1, 2, 3, 4, 5])

In [106]:
np.append(arr_one, 10)

TypeError: 'tuple' object is not callable

In [87]:
arr_12 = np.arange(12)
print(arr_12 + 1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [89]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [102]:
np.delete(arr1, 0, axis=0)

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [107]:
arr_unsort = np.array([2, 4, 9, 10, 1, 3,])
print(arr_unsort)
np.sort(arr_unsort)

[ 2  4  9 10  1  3]


array([ 1,  2,  3,  4,  9, 10])

In [108]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [115]:
arr1[0] = ([18, 9, 6, 8])
print(arr1)

[[18  9  6  8]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [122]:
print(np.sort(arr1))

[[ 6  8  9 18]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [125]:
print(arr1.sum())
print(arr1.mean()) 
print(arr1.max()) 
print(arr1.min())

109
9.083333333333334
18
5
